apps/silencer/silencer/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'silencer.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('silencer_app.urls')),
]

apps/silencer/silencer_app/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    #url(r'^$', views.search_form),
    #url(r'^search-form/$', views.search_form),
    url(r'^silencer$', views.getData),
]

apps/silencer/silencer_app/models.py
from django.db import models
import datetime

# Create your models here.
class service_details(models.Model):
    service_id = models.IntegerField(primary_key=True) 
    app_name = models.CharField(max_length=100,null=True)
    app_group = models.CharField(max_length=100,null=True)
    group_id = models.CharField(max_length=100,null=True) 
    datacenter = models.CharField(max_length=100,null=True)
    hostnames = models.CharField(max_length=100,null=True)
    wily_alert = models.CharField(max_length=100,null=True)
    wily_mom = models.CharField(max_length=100,null=True)
    Spectrum = models.CharField(max_length=100,null=True)
    Sitescope = models.CharField(max_length=100,null=True)
    PagerDuty = models.CharField(max_length=100,null=True)
    P_Services = models.CharField(max_length=100,null=True)
    P_Token = models.CharField(max_length=100,null=True)
    P_SubDomain = models.CharField(max_length=100,null=True)
    Splunk = models.CharField(max_length=100,null=True)
    Wily = models.CharField(max_length=100,null=True)
    NewRelic = models.CharField(max_length=100,null=True)
 

apps/silencer/silencer_app/forms.py
from django import forms

class SilencerForm(forms.Form):
    #filer = forms.CharField(max_length=1000,required=True,label='Filer Name',widget=forms.TextInput(attrs={'placeholder': 'e.g: qyfiler063a, lvfiler702a','class':'special', 'size': '25'}))
    
    
    
    CHOICES=[('qdc','QDC'),
          ('lvdc','LVDC')]
    datacenter = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect(),initial='qdc')

apps/silencer/silencer_app/views.py
from django.http import HttpResponseRedirect 
from django.shortcuts import render 
from datetime import datetime
import datetime
from silencer_app.forms import SilencerForm
from silencer_app.models import service_details
from django.db import connection
import requests
import json 
from collections import Counter,OrderedDict

def getData(request):

	if request.method == 'GET' and 'getservicenames' not in request.GET:
		form = SilencerForm(request.GET)
		print form
		if form.is_valid():
			var = form.cleaned_data

			appgroup_drpdn_sql = "select distinct app_group from silencer_app_service_details union select ' Select App Group' as app_group from silencer_app_service_details order by app_group ;"
			print appgroup_drpdn_sql
			cursor = connection.cursor()
			cursor.execute(appgroup_drpdn_sql)
			total_rows = cursor.fetchall()
			print total_rows
			app_drpdn_data = []
			li=[list(i) for i in total_rows]
			for i in li:
				temp = {}
				temp['app_group'] = str(i[0])
				app_drpdn_data.append(temp)
				cursor.close()
			#service_names = getServiceDetails('ICS1')
			service_names = 0
			return render(request, 'results.html', {'form': form,'app_drpdn_data':app_drpdn_data,'service_names':service_names})

		else:
			appgroup_drpdn_sql = "select distinct app_group from silencer_app_service_details union select ' Select App Group' as app_group from silencer_app_service_details order by app_group ;"
			print appgroup_drpdn_sql
			cursor = connection.cursor()
			cursor.execute(appgroup_drpdn_sql)
			total_rows = cursor.fetchall()
			print total_rows
			app_drpdn_data = []
			li=[list(i) for i in total_rows]
			for i in li:
				temp = {}
				temp['app_group'] = str(i[0])
				app_drpdn_data.append(temp)
				cursor.close()
			return render(request, 'index.html', {'form': form,'app_drpdn_data':app_drpdn_data})
	elif request.method == 'GET' and 'getservicenames' in request.GET: #this parameter comes from submit type from view index
		form = SilencerForm(request.GET) 
		appgroup_drpdn_sql = "select distinct app_group from silencer_app_service_details union select ' Select App Group' as app_group from silencer_app_service_details order by app_group ;"
		print appgroup_drpdn_sql
		cursor = connection.cursor()
		cursor.execute(appgroup_drpdn_sql)
		total_rows = cursor.fetchall()
		print total_rows
		app_drpdn_data = []
		li=[list(i) for i in total_rows]
		for i in li:
			temp = {}
			temp['app_group'] = str(i[0])
			app_drpdn_data.append(temp)
			cursor.close()
		service_names,service_count = getServiceDetails('ICS')
		#service_names = None
		return render(request, 'results.html', {'form': form,'app_drpdn_data':app_drpdn_data,'service_names':service_names,'service_count':service_count})






def getServiceDetails(domain):
	service_data = {}
	if domain == "ICS":
		print "i am here in ICD block"
		API_ACCESS_KEY = '4vSp3jL1aYfNEeKEwWGT'
		SUBDOMAIN = 'ics-intuit'
		
		headers = {
        'Authorization': 'Token token={0}'.format(API_ACCESS_KEY),
        'Content-type': 'application/json',
    	}
    	
    	count = [0,100,200,300,400,500]
    	for i in count:
	    	payload = {
	    	'offset' : i,'limit' : 100
	    	#'since': format_date(fromdate),'until': format_date(todate)
	    	#'status':'triggered,acknowledged,resolved','since': format_date(since),'until': format_date(until)
	    	#, 'fields':'incident_number,service,created_on,trigger_summary_data'
	    	}
	    	r = requests.get(
	            'https://{0}.pagerduty.com/api/v1/services'.format(SUBDOMAIN),
	            headers=headers,
	            params=payload,
	    	)
	    	output_json = json.loads(r.text)
	    	#print r.text
	    	#print i
	    	for key in output_json['services']:
	        	service_name = str(key['name'])
	        	service_key = str(key['service_key'])
	        	status = str(key['status'])
	        	service_id = str(key['id'])
	        	service_data[service_name] = [service_name]
	        	service_data[service_name].append(service_key)
	        	service_data[service_name].append(status)
	        	service_data[service_name].append(service_id)
	        #for key in output_json['services']:
	        #	temp = {}
            #    temp ['service_name'] = str(key['name'])
            #    temp ['service_key'] = str(key['service_key'])
            #    temp ['status'] = str(key['status'])
            #    service_data.append(temp)
		print len(service_data)

		service_data = OrderedDict(sorted(Counter(service_data).items()))
		service_count = len(service_data)

    	return service_data,service_count
	    
    	
	        
	        
	        
	         
	            
	            
	            
	        
	        
    	
    		

apps/silencer/silencer_app/templates/silencer_app/index.html
{% load staticfiles %}

<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script> 
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/drilldown.js"></script>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="{% static 'css/myapp.css' %}">
<link href='http://fonts.googleapis.com/css?family=Maven+Pro' rel='stylesheet' type='text/css'>
</head>

<div style="padding:0px;margin:5px;height:50px;background-color:#F7D358;margin:0 auto; border-radius:05px;width:85%;border-radius:10px;margin: 10px auto;border:1px solid black;">
           <h1  style = "float: left;margin-left:10px;"align=center""></i><font size="5" color=black>Silencer</font>
            </h1>
</div>


<div style="width:85%;border-radius:10px;height:50px;margin: 10px auto;border:1px solid black;">
    <div>
        <div style="display: inline-block;">
            <form id="form" action="" method="get">
                {% for i in form %}
                    <tr>
                       
                                {% if i.auto_id == "id_datacenter"%} &nbsp;&nbsp;&nbsp;
                                <td>{{ i.label_tag }}</td>
                                {% for radio in form.datacenter %}
                                    <div style="display: inline-block;margin: 15px auto;margin-left: 10px">
                                        {{ radio }}
                                    </div>
                                {% endfor %}
                                {% endif%}
                            &nbsp;

                        
                    </tr>  
                {% endfor %}

                <div style="display: inline-block;margin: 15px auto;margin-left: 10px">
                                <select name="app_group" id="id_app_group">
                                    {% for app_drpdn_data in app_drpdn_data %}
                                    <option value="{{ app_drpdn_data.app_group }}">{{ app_drpdn_data.app_group }}</option>
                                    {% endfor %}
                                </select>
                        </div>
                            &nbsp;&nbsp;
                <input id="submitbtn" type="submit" value="Submit">
                {% csrf_token %}
                <input style = "float: right;margin: 15px auto;margin-left:580px; " id="submitbtn" type="submit" value="Get Service Names" name="getservicenames">

                <script src="{% static "js/spin.min.js" %}" type="text/javascript"></script>
                <script src="{% static "js/loadgif.js" %}" type="text/javascript"></script>

            </form>
        </div>

    </div>
</div>

apps/silencer/silencer_app/templates/silencer_app/results.html
{% load staticfiles %}

<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script> 
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/drilldown.js"></script>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="{% static 'css/myapp.css' %}">
<link href='http://fonts.googleapis.com/css?family=Maven+Pro' rel='stylesheet' type='text/css'>
</head>

<div style="padding:0px;margin:5px;height:50px;background-color:#F7D358;margin:0 auto; border-radius:05px;width:85%;border-radius:10px;margin: 10px auto;border:1px solid black;">
           <h1  style = "float: left;margin-left:10px;"align=center""></i><font size="5" color=black>Silencer</font>
            </h1>
</div>


<div style="width:85%;border-radius:10px;height:50px;margin: 10px auto;border:1px solid black;">
    <div>
        <div style="display: inline-block;">
            <form id="form" action="" method="get">
                {% for i in form %}
                    <tr>
                       
                                {% if i.auto_id == "id_datacenter"%} &nbsp;&nbsp;&nbsp;
                                <td>{{ i.label_tag }}</td>
                                {% for radio in form.datacenter %}
                                    <div style="display: inline-block;margin: 15px auto;margin-left: 10px">
                                        {{ radio }}
                                    </div>
                                {% endfor %}
                                {% endif%}
                            &nbsp;

                        
                    </tr>  
                {% endfor %}

                <div style="display: inline-block;margin: 15px auto;margin-left: 10px">
                                <select name="app_group" id="id_app_group">
                                    {% for app_drpdn_data in app_drpdn_data %}
                                    <option value="{{ app_drpdn_data.app_group }}">{{ app_drpdn_data.app_group }}</option>
                                    {% endfor %}
                                </select>
                        </div>
                            &nbsp;&nbsp;
                <input id="submitbtn" type="submit" value="Submit">
                {% csrf_token %}
                <input style = "float: right;margin: 15px auto;margin-left:580px; " id="submitbtn" type="submit" value="Get Service Names" name="getservicenames">

                <script src="{% static "js/spin.min.js" %}" type="text/javascript"></script>
                <script src="{% static "js/loadgif.js" %}" type="text/javascript"></script>

            </form>
        </div>

    </div>
</div>


{% if service_count >= 0 %}

<div style="width:85%;margin:0 auto;">
	<div style="padding:10px;font-weight: bold;">{{"Total Number of Services : "}}{{service_count}}<br> </div>
                <input type="text"  id="search1" placeholder="Type to filter records" class= "form-control" font-size: 10pt; >  
                                <table class="table table-hover table-condensed;border-radius:10px;">

                                  <thead style="background-color:rgb(26, 188, 156);">    
                                      <th><font color=white size="2">Service Name </font> </th>
                                      <th><font color=white size="2">Service Key </font> </th>
                                      <th><font color=white size="2">Service ID</font></th>
                                      <th><font color=white size="2">Status</font></th> 
                                  </thead>


                                  <tbody>
                                    {% for i,j in service_names.items %}
                                      <tr  class="status" value="alert"> 
                                             
                                                    <td class><font size="2"</font>{{i}}</div>
                                                    <td class><font size="2"</font>{{j.1}}</div>
                                                    <td class><font size="2"</font>{{j.3}}</div>
                                                    <td class><font size="2"</font>{{j.2}}</div> 
                                    </tr>
                                    {% endfor %}
                                  </tbody>
                                </table> 
             
 </div>
 {% endif %}



<script type="text/javascript">




function show() {
    document.getElementById("myDiv").style.display="block";
    setTimeout("hide()", 5000);  // 5 seconds
}

function hide() {
    document.getElementById("myDiv").style.display="none";
}


        
  var $rows = $('tr.status[value=alert]');
  $('#search1').keyup(function() {
  var val = $.trim($(this).val()).replace(/ +/g, ' ').toLowerCase();
    
  $rows.show().filter(function() {
        var text = $(this).text().replace(/\s+/g, ' ').toLowerCase();
        return !~text.indexOf(val);
    }).hide();
  });
</script>